# Generated by Django 4.2.3 on 2023-07-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Your default value here', max_length=200),
        ),
    ]
